language: php

php: 7.1

sudo: false

env:
  - APP_KEY=base64:xIqp823QoWI8aYcDVlMpLlhFDodhCIFpwh0VQe6CEtg=

cache:
  directories:
    - vendor

before_script:
  - composer install

script: vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

deploy:
  provider: script
  script: curl ${ENVOYER_DEPLOYMENT_HOOK}?sha=${TRAVIS_COMMIT}
  on:
    branch: master
    
addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN
